// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Recharts from "recharts";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Pie$Recharts from "@float-capital/rescript-recharts/src/Pie.bs.js";

function PieChart(Props) {
  var data = Props.data;
  var displayCell = function (data) {
    return Belt_Array.map(data, (function (entry) {
                  console.log(entry.color);
                  return React.createElement(Recharts.Cell, {
                              fill: "#ff9896",
                              key: "cell-" + String(entry.uv)
                            });
                }));
  };
  return React.createElement(Recharts.PieChart, {
              height: 400,
              width: 800,
              children: React.createElement(Recharts.Pie, Curry.app(Pie$Recharts.makeProps({
                              TAG: /* Px */0,
                              _0: 150
                            }, {
                              TAG: /* Px */0,
                              _0: 250
                            }, {
                              TAG: /* Px */0,
                              _0: 60.0
                            }, {
                              TAG: /* Px */0,
                              _0: 80.0
                            })(undefined, undefined, undefined, undefined, undefined, undefined, data), [
                        "uv",
                        undefined,
                        "#82ca9d",
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        undefined,
                        Caml_option.some(React.createElement("div", undefined, displayCell(data))),
                        undefined,
                        undefined
                      ]))
            });
}

var make = PieChart;

export {
  make ,
}
/* react Not a pure module */
