// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Float from "rescript/lib/es6/belt_Float.js";

import './SliderInput.css';
;

function SliderInput(Props) {
  var title = Props.title;
  var state = Props.state;
  var underlineTitle = Props.underlineTitle;
  var min = Props.min;
  var max = Props.max;
  var onChange = Props.onChange;
  var v = Belt_Float.fromString("0.01");
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "displayTitle"
                }, React.createElement("span", {
                      className: "title"
                    }, title), React.createElement("span", {
                      className: "underlineTitle"
                    }, underlineTitle)), React.createElement("div", undefined, React.createElement("input", {
                      className: "slider",
                      max: String(max),
                      min: String(min),
                      step: v !== undefined ? v : -1,
                      type: "range",
                      value: String(state),
                      onChange: onChange
                    })));
}

var make = SliderInput;

export {
  make ,
}
/*  Not a pure module */
