// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as PieChart from "./components/PieChart/PieChart.bs.js";
import * as SliderInput from "./components/SliderInputComponent/SliderInput.bs.js";

import "./App.css";
;

function App(Props) {
  var match = React.useState(function () {
        return 1000000.00;
      });
  var setLoanAmt = match[1];
  var loanAmt = match[0];
  var match$1 = React.useState(function () {
        return 6.00;
      });
  var setRateOfInterest = match$1[1];
  var rateOfInterest = match$1[0];
  var match$2 = React.useState(function () {
        return 5.00;
      });
  var setLoanTenure = match$2[1];
  var loanTenure = match$2[0];
  var match$3 = React.useState(function () {
        return 0.00;
      });
  var setInterestAmt = match$3[1];
  var match$4 = React.useState(function () {
        return 0.00;
      });
  var setEmi = match$4[1];
  var data = [
    {
      name: "Principal Amt",
      uv: 100000,
      color: "#0088FE"
    },
    {
      name: "Interest Amt",
      uv: 1000,
      color: "#00C49F"
    }
  ];
  var match$5 = React.useState(function () {
        return data;
      });
  var setChartData = match$5[1];
  var handleEmiChange = function (param) {
    var monthlyROI = rateOfInterest / 12.0 / 100.0;
    var monthlyTenure = loanTenure * 12.0;
    var rateOfInterestPow = Math.pow(1.0 + monthlyROI, monthlyTenure);
    var emiAmt = loanAmt * monthlyROI * rateOfInterestPow / (rateOfInterestPow - 1.0);
    var intAmt = emiAmt * monthlyTenure - loanAmt;
    var pieChartData = [
      {
        name: "Principal Amt",
        uv: loanAmt | 0,
        color: "#0088FE"
      },
      {
        name: "Interest Amt",
        uv: intAmt | 0,
        color: "#00C49F"
      }
    ];
    Curry._1(setChartData, (function (param) {
            return pieChartData;
          }));
    Curry._1(setInterestAmt, (function (param) {
            return intAmt;
          }));
    Curry._1(setEmi, (function (param) {
            return emiAmt;
          }));
  };
  var handleLoanAmtInput = function (e) {
    Curry._1(setLoanAmt, e.target.value);
  };
  var handleRateOfInterest = function (e) {
    Curry._1(setRateOfInterest, e.target.value);
  };
  var handleLoanTenure = function (e) {
    Curry._1(setLoanTenure, e.target.value);
  };
  React.useEffect((function () {
          handleEmiChange(undefined);
        }), [
        loanAmt,
        rateOfInterest,
        loanTenure
      ]);
  return React.createElement("div", {
              className: "App"
            }, React.createElement("span", {
                  className: "title"
                }, "EMI Calculator"), React.createElement(SliderInput.make, {
                  title: "Loan Amount",
                  state: loanAmt,
                  underlineTitle: "₹ " + String(loanAmt),
                  min: 100000,
                  max: 100000000,
                  onChange: handleLoanAmtInput
                }), React.createElement(SliderInput.make, {
                  title: "Rate of Interest(p.a)",
                  state: rateOfInterest,
                  underlineTitle: String(rateOfInterest) + "%",
                  min: 1,
                  max: 30,
                  onChange: handleRateOfInterest
                }), React.createElement(SliderInput.make, {
                  title: "Loan tenure (years)",
                  state: loanTenure,
                  underlineTitle: String(loanTenure) + "Yr",
                  min: 1,
                  max: 30,
                  onChange: handleLoanTenure
                }), React.createElement("div", {
                  className: "card"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("span", {
                          className: "left-column"
                        }, "Monthly EMI "), React.createElement("span", {
                          className: "right-column"
                        }, String(match$4[0] | 0))), React.createElement("div", {
                      className: "container"
                    }, React.createElement("span", {
                          className: "left-column"
                        }, "Principal Amount "), React.createElement("span", {
                          className: "right-column"
                        }, String(loanAmt | 0))), React.createElement("div", {
                      className: "container"
                    }, React.createElement("span", {
                          className: "left-column"
                        }, "Interest Amount "), React.createElement("span", {
                          className: "right-column"
                        }, String(match$3[0] | 0))), React.createElement("div", {
                      className: "display-pie-chart"
                    }, React.createElement(PieChart.make, {
                          data: match$5[0]
                        }))));
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
